export { init } from './commands/init'
export * from './constants'
export * from './types'
export * from './utils/claude-config'
export * from './utils/config'
export * from './utils/installer'
export { cleanupPermissions, mergeAndCleanPermissions } from './utils/permission-cleaner'
export { commandExists, getPlatform } from './utils/platform'
export { importRecommendedEnv, importRecommendedPermissions, openSettingsJson } from './utils/simple-config'
